version: "1.0"

volumes:
  oracle_data:
    driver: local  # Oracle DB의 데이터 저장을 위한 볼륨    

networks:
  default:
    name: oracle
    external: false

services:
  oracle:
    image: container-registry.oracle.com/database/express:${ORACLE_VERSION}
    container_name: oracle-xe
    environment:
      - ORACLE_PWD=${ORACLE_PASSWORD}  # Oracle Database의 SYS 및 SYSTEM 계정 관리자 비밀번호
      - ORACLE_CHARACTERSET=AL32UTF8  # 문자 집합 설정
      - TZ=Asia/Seoul

    ports:
      - "1521:1521"  # Oracle DB의 기본 포트
      - "5500:5500"  # Oracle Management 서비스 포트
    volumes:
      - oracle_data:/opt/oracle/oradata  # 데이터 저장을 위한 볼륨
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "SYSTEM/${ORACLE_PASSWORD}@//localhost:1521/XEPDB1", "SELECT 1 FROM dual;"]
      interval: 30s
      timeout: 30s
      retries: 5
